In [2]:
import torch
import numpy as np

## Tensores

In [3]:
 torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Propriedades basicas de aritimetica de tensores

In [4]:
A = torch.arange(6, dtype = torch.float32).reshape(2, 3)
B = A.clone()
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

## Handamard product denotado por ⊙ ou produto de elementos de duas matrizes

In [5]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [6]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## Reducao

In [9]:
x = torch.arange(3, dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [10]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [11]:
A.shape, A.sum(axis = 0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [12]:
A.shape, A.sum(axis = 1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [13]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [14]:
A.mean(axis = 0), A.sum(axis = 0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

## Non reduction sum

In [15]:
sum_A = A.sum(axis = 1, keepdims = True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [16]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [17]:
A.cumsum(axis = 0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

## Dot products

In [18]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [19]:
torch.sum(x * y)

tensor(3.)

Produto matrix vetor

In [20]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

## Produto matricial

In [22]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

## Norma <br>
informalmente serve para dizer o quao grande e um vetor norma ell2 mede a distancia euclidiana <br>
A norma tem as seguintes propriedades: <br>
1 - Dado um vetor, se escalanonarmos o vetor por um escalar a pertencente aos reais sua norma escala aumenta tambem<br>
2 - Para qualquer vetor x e y as normas satisfazem a desigualdade triangular <br>
3 - A norma de um vetor e nao negativa e apenas some se o vetor for zero

In [23]:
u = torch.tensor([3., -4.])
torch.norm(u)

tensor(5.)

## Distancia manhattan

In [24]:
torch.abs(u).sum()

tensor(7.)

## Calculando a norma fobenius de uma matriz

In [25]:
torch.norm(torch.ones((4,9)))

tensor(6.)